# Generated by Django 5.1.3 on 2024-11-23 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_incoming_date_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='incoming_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 17, 10, 58, 338870, tzinfo=datetime.timezone.utc)),
        ),
    ]
