# Generated by Django 5.1.3 on 2024-11-23 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_incoming_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='incoming_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
